### ISSUE TITLE
Additional dev dependencies

### ISSUE THREAD

**Issue by kernalphage** [adrianiainlam/facial-landmarks-for-cubism#2]
Cheers for publishing this!
I'm running Debian Bullseye and was able to get it working with only a little more massaging.

There were a few more dev dependencies I needed to add to make the project work: 
`libopencv-dev libopenblas-dev liblapack-dev`

**Comment by adrianiainlam** [comment]
Thanks for letting me know! I'm add this to the README next time I push an update :)
